mass: 0.032        # Wheel mass in Kg
radius: 0.05    # Wheel radius in m
length: 0.05     # Wheel length in m, considering is as a cylinder
mesh: '../components/DDSM115.stl'  # Leave it empty ('') to have a red wheel
scale: '0.001 0.001 0.001'
x_offset: 0.11
y_offset: 0.03
z_offset: -0.05
